### ISSUE TITLE
32bit version

### ISSUE THREAD

**Issue by ghazel** [beuaaa/pywinauto_recorder#13]
Could you provide a 32bit standalone application as well? The environment I'm running in does not support 64bit.

**Comment by beuaaa** [comment]
I can't provide you with a 32-bit version because it is not certain that the 32bit version that I will be able to compile on my PC will work on your PC because of this [issue](https://github.com/beuaaa/pywinauto_recorder/issues/9) .

To make sure you have a 32-bit executable running on your PC you need to recompile Pywinauto_recorder.exe yourself. 
I have just archived under github the necessary files to compile. 

Here is the procedure to follow:
- Download the [clone](https://github.com/beuaaa/pywinauto_recorder/archive/master.zip)
- Install Nuitka
- Replace the absolute path of python.exe with your 32bit python in bin/make_exe-Pyhton3.8.bat
- Install ResourceHacker.exe (it is just to update the icon of the executable)
- Run make_exe-Pyhton3.8.bat

Feel free to ask me for help if you can't recompile.
