### ISSUE TITLE
Pywinauto_recorder.exe does not work on all PC

### ISSUE THREAD

**Issue by beuaaa** [beuaaa/pywinauto_recorder#9]
On some machines pywinauto_recorder.exe does not work and the following error message is displayed:
`module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'

Pywinauto_rercoder.exe is compiled with [Nuitka ](http://nuitka.net/)

I think it has something to do with this  [Pywinauto issue ...](https://github.com/pywinauto/pywinauto/issues/911) but i'am not sure.

**Comment by vasily-v-ryabov** [comment]
The referenced pywinauto issue is different. The problem is that you're packing your tool into single executable, but "uia" backend uses `comtypes` module as a dependency. `comtypes` generates Python wrapper around `UIAutomationCore.dll` and saves it to some local disk location called "comtypes cache". If you clear this cache (first you need to know the location), your executable will most likely work on this clean machine.

One of the permanent solutions could be packing already generated UIAutomationCode.dll wrapper into executable, but you may face another problem: different version of UIAutomationCode.dll on another machine that will mismatch with the packed auto-generated code. So you have to pack UIAutomationCode.dll as well as its binary dependencies that could be discovered using DependencyWalker tool. But it's also dangerous to mismatch with some system libraries like `kernel32.dll` or `user32.dll`.

So you see that `comtypes` is a serious limitation. I have long-term plans to dive into comtypes code with hope to get the core concept and improve it to make it more dynamic. But this is low priority for now.

**Comment by ghazel** [comment]
`comtypes` has a function to get the `comtypes_cache` directory `comtypes.client._code_cache._find_gen_dir()`, and a handy script to clear it: https://github.com/enthought/comtypes/blob/master/clear_comtypes_cache.py

**Comment by beuaaa** [comment]
I'm still thinking about how to solve the 'Pywinauto_recorder.exe' problem that doesn't work on all machines.

I don't know yet what position to take so I want to share the beginning of a reflection:

The purpose of 'Pywinauto_recorder.exe' is to make it easy to record and replay a Python script. It's just packaging to simplify the users life: instead of having to install a Python interpreter, get the github clone of "Pywinauto recorder" and install all the dependencies, 'Pywinauto_recorder.exe' is ready to be used by the user who just has to double click on the executable. 

Compiling with Nuitka or another compiler is not a requirement.

Maybe it would be enough to package a space with a Python interpreter with all the necessary modules for execution. 
Pywinauto_recorder.exe' would then simply call "python.exe pywinauto_recorder.py".

What do you think about this?

**Comment by ghazel** [comment]
My use-case is running `Pywinauto_recorder` in `Wine`, so build scripts might fail. The difference between a single exe and a self-contained directory of runable python+modules is, I think, small.

**Comment by vasily-v-ryabov** [comment]
This code should tell `comtypes` to generate COM wrappers in memory:
```python
import comtypes.client
comtypes.client.gen_dir = None
import pywinauto
```
Also I'm planning to update `comtypes` package soon with some fixes made by their community.

**Comment by beuaaa** [comment]
I tried to put your code to generate COM wrappers in memory but I have this warning and then my recorder does not work anymore:
C:\Users\d_pra\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\__init__.py:80: UserWarning: Revert to STA COM threading mode
  warnings.warn("Revert to STA COM threading mode", UserWarning)

**Comment by vasily-v-ryabov** [comment]
@beuaaa thanks for trying it! This is a new food for thoughts.

**Comment by beuaaa** [comment]
Could you try again with Pywinauto_recorder_exe v>=0.20  and fill this form please?

**Comment by vasily-v-ryabov** [comment]
Hi @beuaaa the splash screen disappears too fast. It's better to let user time to read the instruction and then press the button "Proceed / Start". Couldn't do any recording because of this.

**Comment by beuaaa** [comment]
When you double-click on Pywiauto_recorder.exe, the splash screen is displayed and the mouse cursor is positioned on it. It will remain displayed as long as the mouse cursor does not move. This saves you time when you don't want to read the splash screen. But maybe it would be more ergonomic with a button "Proceed / Start"?

**Comment by vasily-v-ryabov** [comment]
Cursor position is very implicit trigger. It confuses a lot. Please make a button or at least ask user to click on splash screen before closing it.

**Comment by beuaaa** [comment]
I changed the way the splash screen closes. Now a flashing message at the bottom of the splash screen asks the user to move the mouse cursor inside if it was outside before the splash screen appeared and vice versa.

**Comment by beuaaa** [comment]
It seems that the issue has been fixed. Pywinauto-recorder.exe seems to work all PCs since Clear_ComTypes_Cache is always called before an installation.
